apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-cluster-issuer
  namespace: cert-manager
spec:
  acme:
    email: ortega.reynoso@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cloudflare-issuer-account-key
    solvers:
    - selector: {}
      dns01:
        cloudflare:
          email: ortega.reynoso@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token