apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
  labels:
    k8s-app: alertmanager
spec:
  ports:
  - name: http
    port: 9093
    protocol: TCP
    targetPort: 9093
  selector:
    k8s-app: alertmanager
  type: "LoadBalancer"
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-operated
  namespace: monitoring
  labels:
    k8s-app: alertmanager
spec:
  type: "ClusterIP"
  clusterIP: None
  selector:
    k8s-app: alertmanager
  ports:
  - name: mesh
    port: 6783
    protocol: TCP
    targetPort: 6783
  - name: http
    port: 9093
    protocol: TCP
    targetPort: 9093
