apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: alertmanager-secrets
  namespace: monitoring
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/jetstack-maria/secrets/alertmanager-config/versions/latest"
        path: "alertmanager.yml"
